In [1]:
# hmm
import numpy as np

In [3]:
a = np.array([[0.8, 0.1, 0.1],
              [0.4, 0.2, 0.4],
              [0.6, 0.1, 0.3]])
b = np.array([[0.3, 0.7], 
               [0.4, 0.6],
               [0.8, 0.2]])

In [33]:
t = 1   # V 1
# alpha = a[0] * b[:,0]
alpha = np.array([0.3, 0, 0])
alpha

array([0.3, 0. , 0. ])

In [34]:
t = 2  # V2
tmp = np.matmul(a.T, alpha)
alpha = tmp * b[:,1]
alpha

array([0.168, 0.018, 0.006])

In [35]:
t = 3  # V2
tmp = np.matmul(a.T, alpha)
alpha = tmp * b[:,1]
alpha

array([0.10164, 0.0126 , 0.00516])

In [36]:
t = 4  # V1
tmp = np.matmul(a.T, alpha)
alpha = tmp * b[:,0]
alpha

array([0.0268344, 0.00528  , 0.0134016])

In [37]:
t = 5  # V1
tmp = np.matmul(a.T, alpha)
alpha = tmp * b[:,0]
alpha

array([0.00948614, 0.00203184, 0.00705274])

In [38]:
alpha.sum()

0.01857072

In [6]:
from sympy import ImageSet, S, Lambda
from sympy.abc import x

In [7]:
squares = ImageSet(Lambda(x,x**2), S.Naturals)

In [8]:
squares

ImageSet(Lambda(x, x**2), Naturals)

In [9]:
5 in squares

False

In [10]:
16 in squares

True