## Lab #11_2 iris

In [1]:
%matplotlib inline

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np
from itertools import product, combinations
global str


In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('IRISdataSet.txt', sep="[\t]*",engine='python')
data.head()

/home/joshua/anaconda3/envs/PyTorch/lib/python3.6/site-packages/pandas/io/parsers.py:2379: FutureWarning: split() requires a non-empty pattern match.
  yield pat.split(line.strip())
/home/joshua/anaconda3/envs/PyTorch/lib/python3.6/site-packages/pandas/io/parsers.py:2381: FutureWarning: split() requires a non-empty pattern match.
  yield pat.split(line.strip())


Type  PW  PL  SW  SL
0     Setosa   2  14  33  50
1  Verginica  24  56  31  67
2  Verginica  23  51  31  69
3     Setosa   2  10  36  46
4  Verginica  20  52  30  65

In [4]:
data['Type'].unique()

array(['Setosa', 'Verginica', 'Versicolor'], dtype=object)

In [5]:
data['PW'].unique()

array([ 2, 24, 23, 20, 19, 13, 16, 17, 14,  1, 12, 18, 10, 21,  4, 15, 11,
       25,  3, 22,  5,  6])

In [6]:
print(data['PL'].unique())
print(data['SW'].unique())
print(data['SL'].unique())

[14 56 51 10 52 45 47 16 50 13 40 49 33 19 41 15 55 39 57 42 58 44 30 54
 61 36 17 46 59 53 60 12 11 35 48 67 66 38 64 69 37 63 43]
[33 31 36 30 27 28 25 32 26 23 38 29 34 24 42 22 37 35 41 39 20 40 44]
[50 67 69 46 65 58 57 63 49 70 48 44 51 64 60 54 55 52 59 56 72 68 66 62
 61 47 43 77 45 76 79 71 74 73 53]


In [7]:
A = np.array(data['Type'])
B = np.array(data['PW'])
C = np.array(data['PL'])
D = np.array(data['SW'])
E = np.array(data['SL'])

In [8]:
A.shape

(150,)

In [9]:
A_data = A[0:int(A.shape[0] / 2)]
A_test = A[int(A.shape[0] / 2):]
B_data = B[0:int(A.shape[0] / 2)]
B_test = B[int(A.shape[0] / 2):]
C_data = C[0:int(A.shape[0] / 2)]
C_test = C[int(A.shape[0] / 2):]
D_data = D[0:int(A.shape[0] / 2)]
D_test = D[int(A.shape[0] / 2):]
E_data = E[0:int(A.shape[0] / 2)]
E_test = E[int(A.shape[0] / 2):]

In [10]:
set_row = np.where(A_data == 'Setosa')[0]
ver_row = np.where(A_data == 'Versicolor')[0]
vir_row = np.where(A_data == 'Verginica')[0]

In [11]:
ver_row = np.where(A_data == 'Versicolor')[0]
ver_row.shape

(24,)

In [12]:
np.unique(A_data)

array(['Setosa', 'Verginica', 'Versicolor'], dtype=object)

In [13]:
B_set = np.zeros_like(set_row)

In [14]:
B_Set = B_data[set_row]
B_Set

array([2, 2, 2, 1, 2, 2, 2, 4, 2, 2, 4, 2, 2, 1, 3, 4, 2, 2, 2, 2, 1, 2,
       4])

In [15]:
set_row

array([ 0,  3, 10, 12, 13, 17, 18, 20, 21, 24, 26, 29, 32, 45, 46, 48, 58,
       64, 65, 68, 69, 71, 72])

In [16]:
B_set = np.zeros_like(set_row)

In [17]:
B_set.shape

(23,)

In [18]:
B_data[set_row]

array([2, 2, 2, 1, 2, 2, 2, 4, 2, 2, 4, 2, 2, 1, 3, 4, 2, 2, 2, 2, 1, 2,
       4])

In [19]:
def get_features(set_row,ver_row,vir_row,B_data,C_data,D_data,E_data):
    B_set = B_data[set_row]
    B_ver = B_data[ver_row]
    B_vir = B_data[vir_row]
    C_set = C_data[set_row]
    C_ver = C_data[ver_row]
    C_vir = C_data[vir_row]
    D_set = D_data[set_row]
    D_ver = D_data[ver_row]
    D_vir = D_data[vir_row]
    E_set = E_data[set_row]
    E_ver = E_data[ver_row]
    E_vir = E_data[vir_row]
    return B_set,B_ver,B_vir,C_set,C_ver,C_vir,D_set,D_ver,D_vir,E_set,E_ver,E_vir

In [20]:
B_set,B_ver,B_vir,C_set,C_ver,C_vir,D_set,D_ver,D_vir,E_set,E_ver,E_vir = get_features(set_row,ver_row,vir_row,B_data,C_data,D_data,E_data)
B_set.shape

(23,)

In [21]:
np.mean(B_set)

2.260869565217391

In [102]:
set_mean = np.array([np.mean(B_set), np.mean(C_set), np.mean(D_set), np.mean(E_set)])
ver_mean = np.array([np.mean(B_ver), np.mean(C_ver), np.mean(D_ver), np.mean(E_ver)])
vir_mean = np.array([np.mean(B_vir), np.mean(C_vir), np.mean(D_vir), np.mean(E_vir)])
print(set_mean)
print(ver_mean)
print(vir_mean)

[ 2.26086957 14.34782609 33.82608696 49.43478261]
[13.25       41.79166667 27.66666667 59.20833333]
[20.35714286 53.85714286 29.57142857 64.46428571]


In [23]:
set_cov = np.cov(np.vstack([B_set,C_set, D_set, E_set]))
ver_cov = np.cov(np.vstack([B_ver,C_ver, D_ver, E_ver]))
vir_cov = np.cov(np.vstack([B_vir,C_vir, D_vir, E_vir]))
np.cov(np.vstack([B_set,C_set, D_set, E_set]))

array([[ 0.83794466,  0.99604743,  1.13833992,  1.47233202],
       [ 0.99604743,  3.87351779,  1.79051383,  3.25098814],
       [ 1.13833992,  1.79051383, 11.87747036,  8.66996047],
       [ 1.47233202,  3.25098814,  8.66996047, 13.80237154]])

In [24]:
B_vir,C_vir, D_vir, E_vir

(array([24, 23, 20, 19, 17, 19, 18, 21, 19, 18, 15, 23, 20, 18, 21, 25, 21,
        22, 15, 23, 23, 25, 18, 23, 21, 18, 18, 23]),
 array([56, 51, 52, 51, 45, 50, 49, 56, 51, 55, 50, 57, 49, 58, 54, 61, 55,
        56, 51, 59, 54, 57, 51, 53, 57, 60, 49, 61]),
 array([31, 31, 30, 27, 25, 25, 27, 28, 27, 31, 22, 32, 28, 25, 31, 36, 30,
        28, 28, 32, 34, 33, 30, 32, 33, 32, 30, 30]),
 array([67, 69, 65, 58, 49, 63, 63, 64, 58, 64, 60, 69, 56, 67, 69, 72, 68,
        64, 63, 68, 62, 67, 59, 64, 67, 72, 61, 77]))

In [25]:
np.size(set_row)

23

In [26]:
p_set = np.size(set_row)/75
p_ver = np.size(ver_row)/75
p_vir = np.size(vir_row)/75

In [27]:
p_set

0.30666666666666664

In [28]:
set_row_test = np.where(A_test == 'Setosa')[0]
ver_row_test = np.where(A_test == 'Versicolor')[0]
vir_row_test = np.where(A_test == 'Verginica')[0]
set_row_test

array([ 1,  4,  5,  8, 10, 12, 13, 16, 20, 21, 23, 26, 30, 36, 38, 41, 42,
       44, 47, 48, 56, 58, 60, 66, 69, 72, 74])

In [29]:
A_test_new = np.zeros((75,))

In [30]:
A_test_new[set_row_test]  = 1
A_test_new[ver_row_test]  = 2
A_test_new[vir_row_test]  = 3
A_test_new

array([2., 1., 3., 2., 1., 1., 2., 2., 1., 2., 1., 2., 1., 1., 2., 2., 1.,
       3., 2., 2., 1., 1., 2., 1., 3., 2., 1., 2., 2., 3., 1., 3., 3., 3.,
       2., 2., 1., 3., 1., 3., 2., 1., 1., 3., 1., 3., 2., 1., 1., 3., 3.,
       3., 3., 2., 3., 2., 1., 2., 1., 3., 1., 3., 2., 2., 2., 3., 1., 2.,
       3., 1., 3., 2., 1., 3., 1.])

# problem a

In [31]:
cov = (set_cov + ver_cov + vir_cov)/3
cov

array([[ 4.30473472,  5.56744638,  3.72811622,  5.77014625],
       [ 5.56744638, 16.42468421,  5.91061756, 15.59511697],
       [ 3.72811622,  5.91061756, 10.5193899 ,  9.26741187],
       [ 5.77014625, 15.59511697,  9.26741187, 25.73930558]])

In [32]:
from sympy import symbols
from sympy import Matrix
import sympy

In [33]:
def decision_boundaries(mu,cov,pwi,x):
    W1 = -0.5 * np.linalg.inv(cov)
    w1 = np.linalg.inv(cov) @ mu
    w10 = -0.5 * mu.T @ np.linalg.inv(cov) @ mu - \
            -0.5 * np.log(np.linalg.det(cov)) + np.log(pwi)
    g = x.T * Matrix(W1) * x + Matrix(w1[:,np.newaxis].T) * x + Matrix([w10])
    return g

In [34]:
x1, x2, x3, x4 = symbols('x1, x2, x3, x4')
X1 = Matrix([x1, x2, x3, x4])

In [63]:
g_set1 = decision_boundaries(set_mean,cov,p_set,X1)
g_ver1 = decision_boundaries(ver_mean,cov,p_ver,X1)
g1 = g_set1 - g_ver1  

g_set2 = decision_boundaries(set_mean,cov,p_set,X1)
g_vir1 = decision_boundaries(vir_mean,cov,p_vir,X1)
g2 = g_set2 - g_vir1

g_ver2 = decision_boundaries(ver_mean,cov,p_ver,X1)
g_vir2 = decision_boundaries(vir_mean,cov,p_vir,X1)
g3 = g_ver2 - g_vir2
error = 0

In [64]:
g_set1

Matrix([[x1*(-0.243249872662931*x1 + 0.069983647527399*x2 + 0.0530186903886203*x3 - 0.00696063335493801*x4) - 3.80694880898707*x1 + x2*(0.0699836475273989*x1 - 0.0919360601901596*x2 - 0.0122985447461029*x3 + 0.044442279423805*x4) - 1.24024814791916*x2 + x3*(0.0530186903886203*x1 - 0.0122985447461028*x2 - 0.0812895848980979*x3 + 0.0248342251565159*x4) + 3.15724616641455*x3 + x4*(-0.00696063335493801*x1 + 0.044442279423805*x2 + 0.0248342251565159*x3 - 0.0537336822203196*x4) + 2.38871045542044*x4 - 96.4819316002507]])

In [65]:
i = 0
g1.subs([(x1, B_test[i]),(x2, C_test[i]),(x3, D_test[i]),(x4, E_test[i])])[0]

-53.6229888252528

In [66]:
f = open('Result_a.txt','a+')
for i in range(A_test.shape[0]):
    J1 = g1.subs([(x1, B_test[i]),(x2, C_test[i]),(x3, D_test[i]),(x4, E_test[i])])[0]
    J2 = g2.subs([(x1, B_test[i]),(x2, C_test[i]),(x3, D_test[i]),(x4, E_test[i])])[0]
    J3 = g3.subs([(x1, B_test[i]),(x2, C_test[i]),(x3, D_test[i]),(x4, E_test[i])])[0]
    if J1>0 and J2>0:
        s = str(i+1)+ ' belong to set \n'
        num = 1
        f.write(s)
    elif J1<0 and J3>0:
        s = str(i+1)+ ' belong to ver \n'
        num = 2
        f.write(s)
    elif J2<0 and J3<0:
        s = str(i+1)+ ' belong to vir \n'
        num = 3
        f.write(s)
    
    if num != A_test_new[i]:
        error = error + 1
    
p_error = error / A_test.shape[0]
s = '--------------number of misclassified points:' + str(error) + '\n'
f.write(s)
s = '--------------misclassify probability:' + str(p_error) + '\n'
f.write(s)
f.close()

In [48]:
A_test_new

array([2., 1., 3., 2., 1., 1., 2., 2., 1., 2., 1., 2., 1., 1., 2., 2., 1.,
       3., 2., 2., 1., 1., 2., 1., 3., 2., 1., 2., 2., 3., 1., 3., 3., 3.,
       2., 2., 1., 3., 1., 3., 2., 1., 1., 3., 1., 3., 2., 1., 1., 3., 3.,
       3., 3., 2., 3., 2., 1., 2., 1., 3., 1., 3., 2., 2., 2., 3., 1., 2.,
       3., 1., 3., 2., 1., 3., 1.])

# problem b

In [67]:
f = open('Result_b.txt','a+')

g_set1 = decision_boundaries(set_mean,set_cov,p_set,X1)
g_ver1 = decision_boundaries(ver_mean,ver_cov,p_ver,X1)
g1 = g_set1 - g_ver1       
g_set2 = decision_boundaries(set_mean,set_cov,p_set,X1)
g_vir1 = decision_boundaries(vir_mean,vir_cov,p_vir,X1)
g2 = g_set2 - g_vir1
g_ver2 = decision_boundaries(ver_mean,ver_cov,p_ver,X1)
g_vir2 = decision_boundaries(vir_mean,vir_cov,p_vir,X1)
g3 = g_ver2 - g_vir2
error = 0
# f = open('Result_a.txt','a+')
for i in range(A_test.shape[0]):
    J1 = g1.subs([(x1, B_test[i]),(x2, C_test[i]),(x3, D_test[i]),(x4, E_test[i])])[0]
    J2 = g2.subs([(x1, B_test[i]),(x2, C_test[i]),(x3, D_test[i]),(x4, E_test[i])])[0]
    J3 = g3.subs([(x1, B_test[i]),(x2, C_test[i]),(x3, D_test[i]),(x4, E_test[i])])[0]
    if J1>0 and J2>0:
        s = str(i+1)+ ' belong to set \n'
        num = 1
        f.write(s)
    elif J1<0 and J3>0:
        s = str(i+1)+ ' belong to ver \n'
        num = 2
        f.write(s)
    elif J2<0 and J3<0:
        s = str(i+1)+ ' belong to vir \n'
        num = 3
        f.write(s)
    
    if num != A_test_new[i]:
        error = error + 1
    
p_error = error / A_test.shape[0]
s = '--------------number of misclassified points:' + str(error) + '\n'
f.write(s)
s = '--------------misclassify probability:' + str(p_error) + '\n'
f.write(s)
f.close()

# problem c

In [97]:
def parzen(w,h,x):
    num_class = len(w)
    r=np.zeros((num_class))
    for i in range(num_class):
      hn=h
      rows, _ = w[i].shape
      for j in range(rows):
          hn=hn/np.sqrt(j+1)
          r[i]=r[i]+np.exp( -np.dot((x-w[i][j,:]), (x-w[i][j,:])) / (2*hn**2)) / (np.sqrt(2*np.pi)*hn)
      r[i]=r[i]/rows
    return r

In [79]:
f = open('Result_c.txt','a+')
B_var = np.var(B_data)
C_var = np.var(C_data)
D_var = np.var(D_data)
E_var = np.var(E_data)
cov = np.diag([B_var,C_var,D_var,E_var])
cov

array([[ 59.74222222,   0.        ,   0.        ,   0.        ],
       [  0.        , 285.97226667,   0.        ,   0.        ],
       [  0.        ,   0.        ,  16.27555556,   0.        ],
       [  0.        ,   0.        ,   0.        ,  63.71662222]])

In [73]:
np.vstack([B_np,C_np,D_np,E_np]).shape

(4, 1)

In [76]:
B_var

59.74222222222222

In [85]:
h = 10.0
w1 = np.vstack([B_set, C_set, D_set, E_set]).T
w1.shape

(23, 4)

In [87]:
w2 = np.vstack([B_ver, C_ver, D_ver, E_ver]).T
w2.shape

(24, 4)

In [88]:
w3 = np.vstack([B_vir, C_vir, D_vir, E_vir]).T
w3.shape

(28, 4)

In [90]:
X = [w1, w2, w3]
X[0].shape

(23, 4)

In [92]:
test = np.vstack([B_test, C_test, D_test, E_test]).T
test.shape

(75, 4)

In [101]:
error = 0
for i in range(A_test.shape[0]):
    r=parzen(X,h,test[i,:])
    num=np.where(r==np.max(r))[0] + 1
    if num == 1:
        s = str(i+1)+ ' belong to set \n'
        f.write(s)
    elif num == 2:
        s = str(i+1)+ ' belong to ver \n'
        f.write(s)
    elif num == 3:
        s = str(i+1)+ ' belong to vir \n'
        f.write(s)

    if num != A_test_new[i]:
        error = error + 1
p_error = error / A_test.shape[0]
s = '--------------number of misclassified points:' + str(error) + '\n'
f.write(s)
s = '--------------misclassify probability:' + str(p_error) + '\n'
f.write(s)
f.close()

In [95]:
A_test.shape[0]

75